name: api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test api
      working-directory: ./api
      run: go test -v ./...
      
    - name: Test Coverage api
      working-directory: ./api
      run: go test -cover ./...

    - name: Build api
      working-directory: ./api
      run: go build -v ./...

  
