name: sports

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test sports
      working-directory: ./sports
      run: go test -v ./...
      
    - name: Test Coverage Sports
      working-directory: ./sports
      run: go test -cover ./...

    - name: Build Sports
      working-directory: ./sports
      run: go build -v ./...